-- режим MODE=PostgreSQL;
---  url: jdbc:h2:file:./db/filmorate;DATABASE_TO_UPPER=FALSE;MODE=PostgreSQL;
--CREATE TABLE IF NOT EXISTS "users" (
--  "user_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--  "login" varchar(50) NOT NULL,
--  "email" varchar(50) NOT NULL,
--  "name" varchar(50),
--  "birthday" date NOT NULL
--);
--
--CREATE TABLE IF NOT EXISTS "friends" (
--  "friend_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--  "user1_id" bigint,
--  "user2_id" bigint
--);
--
--CREATE TABLE IF NOT EXISTS "films" (
--  "film_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--  "name" varchar(50) NOT NULL,
--  "duration" int NOT NULL,
--  "description" varchar(100),
--  "release_date" date NOT NULL,
--  "rating_id" int
--);
--
--CREATE TABLE IF NOT EXISTS "genre" (
--  "genre_id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--  "genre_name" varchar(50) NOT NULL
--);
--
--CREATE TABLE IF NOT EXISTS "genre_list" (
--  "genre_list_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--  "film_id" bigint,
--  "genre_id" int
--);
--
--CREATE TABLE IF NOT EXISTS "likes" (
--  "like_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--  "user_id" bigint,
--  "film_id" bigint
--);
--
--CREATE TABLE IF NOT EXISTS "rating" (
--  "rating_id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--  "rating_name" varchar(50) NOT NULL
--);
--
--ALTER TABLE "friends" ADD FOREIGN KEY ("user1_id") REFERENCES "users" ("user_id");
--ALTER TABLE "friends" ADD FOREIGN KEY ("user2_id") REFERENCES "users" ("user_id");
--ALTER TABLE "films" ADD FOREIGN KEY ("rating_id") REFERENCES "rating" ("rating_id");
--ALTER TABLE "genre_list" ADD FOREIGN KEY ("film_id") REFERENCES "films" ("film_id");
--ALTER TABLE "genre_list" ADD FOREIGN KEY ("genre_id") REFERENCES "genre" ("genre_id");
--ALTER TABLE "likes" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");
--ALTER TABLE "likes" ADD FOREIGN KEY ("film_id") REFERENCES "films" ("film_id");


-- Скрипт для нативного режима H2
--  url: jdbc:h2:file:./db/filmorate;DATABASE_TO_UPPER=FALSE;
CREATE TABLE IF NOT EXISTS "users" (
  "user_id" bigint not null AUTO_INCREMENT PRIMARY KEY,
  "login" varchar(50) NOT NULL,
  "email" varchar(50) NOT NULL,
  "name" varchar(50),
  "birthday" date NOT NULL
);

CREATE TABLE IF NOT EXISTS "friends" (
  "friend_id" bigint not null AUTO_INCREMENT PRIMARY KEY,
  "user1_id" bigint,
  "user2_id" bigint
);

CREATE TABLE IF NOT EXISTS "films" (
  "film_id" bigint not null AUTO_INCREMENT PRIMARY KEY,
  "name" varchar(50) NOT NULL,
  "duration" int NOT NULL,
  "description" varchar(100),
  "release_date" date NOT NULL,
  "rating_id" int
);

CREATE TABLE IF NOT EXISTS "genre" (
  "genre_id" int not null AUTO_INCREMENT PRIMARY KEY,
  "genre_name" varchar(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS "genre_list" (
  "genre_list_id" bigint not null AUTO_INCREMENT PRIMARY KEY,
  "film_id" bigint,
  "genre_id" int
);

CREATE TABLE IF NOT EXISTS "likes" (
  "like_id" bigint not null AUTO_INCREMENT PRIMARY KEY,
  "user_id" bigint,
  "film_id" bigint
);

CREATE TABLE IF NOT EXISTS "rating" (
  "rating_id" int not null AUTO_INCREMENT PRIMARY KEY,
  "rating_name" varchar(50) NOT NULL
);

